
networks:
  apicorenet:
    driver: bridge

services:
  data-base:
    image: mysql:9
    container_name: server-database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: apicore
      MYSQL_USER: apicore_user
      MYSQL_PASSWORD: apicore_password
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - "127.0.0.1:3310:3306"
    networks:
      - apicorenet

  redis:
    image: redis:alpine
    container_name: server-cache
    restart: unless-stopped
    networks:
      - apicorenet

  php:
    build:
      context: ./docker/php
    image: apicore_php:1.0
    container_name: server-php
    restart: unless-stopped
    volumes:
      - ./apicore:/var/www/apicore
    working_dir: /var/www/apicore
    depends_on:
      - data-base
      - redis
    networks:
      - apicorenet

  nginx:
    image: nginx:alpine
    container_name: server-web
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./apicore:/var/www/apicore
    depends_on:
      - php
    networks:
      - apicorenet
